name: Deploy Frontend

on:
  push:
    branches:
      - main  # Rulează workflow-ul doar când facem push pe branch-ul `main`

jobs:
  deploy:
    runs-on: ubuntu-latest  # Folosește runner GitHub standard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test SSH Connection
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo SSH Connected Successfully"

      - name: Deploy frontend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/xmu/frontend
            git pull origin main
            cd /var/www/xmu
            docker-compose down
            docker-compose build frontend
            docker-compose up -d
            docker image prune -f
